### ISSUE TITLE
 How to use goproxy-android to convert device into proxy server

### ISSUE THREAD

**Issue by sam3961** [snail007/goproxy-android#4]
Hi,
I am already using frpc Library on my android application as well on the Linux server to convert the device into a proxy server themselves.
Now i am thinking of switching to go-proxy. Can you please guide me step by step on how do i create my mobile device act as a proxy server using custom server which i already have.
I already install go-proxy on my Linux server with the help of read-me so can you please help me to achieve the objective of creating a proxy server from the app so the other users can connect with that particular proxies.

Thank you.
Sumit Kumar

**Comment by snail007** [comment]
https://github.com/snail007/lanass

**Comment by sam3961** [comment]
Thanks @snail007 , Let me try :)

**Comment by sam3961** [comment]
Hi @snail007, I have checked the project compile and run it with my custom server and port(Also open that port on aws) its shows status running now how can i use that Server IP and Port(18.188.1.254:3001) into other device as i tested with http or https proxy on my browser its not working so i am going to use that IP and Port into another device?

![Screenshot_20230831-121726](https://github.com/snail007/goproxy-android/assets/17896222/96e2a80e-f3e6-46ff-bad7-330e5139e1de)
